### ISSUE TITLE
OverflowError: Signed integer value 1 out of range.

### ISSUE THREAD

**Issue by jahnavithota2011** [cantools/cantools#295]
Hi, I getting the following error  when I try to send the following the message.

Message
`BO_ 2227830532 ChargeCart_Heartbeat: 8 ChargeCart
 SG_ ChargeCart_Heartbeat_dummydata : 0|1@1- (1,0) [0|0] ""  BMU`

Code :
`import can
import cantools
from pprint import pprint

class CAN:
        def __init__(self):
                self.bus = can.interface.Bus (bustype = 'socketcan', channel = 'vcan0')
                self.db = cantools.database.load_file('/root/common-all/Data/2018CAR.dbc')

        def send_msg(self, id, data):

                flag = False

                try:
                        check_message = self.db.get_message_by_name(id)
                        flag = True
                        print('Found')
                        pprint(check_message.signals)
                except KeyError:
                        print('Message not found in list')
                if flag:
                        try:
                                encoded_data = check_message.encode(data)
                                message = can.Message(arbitration_id = check_message.frame_id, data = encoded_data)
                                self.bus.send(message)
                                print('Message sent')
                        except can.CanError:
                                print('Message not sent')

if __name__ == '__main__':
        Can = CAN()
        Can.send_msg('TempCoolantLeft',{'TempOutletRadMotorLeft' : 40, 'TempInletRadMotorLeft' : 0 })
        Can.send_msg('ChargeCart_Heartbeat',{'ChargeCart_Heartbeat_dummydata' : 1 })`

Error:
`  File "msg_send.py", line 35, in <module>
    Can.send_msg('ChargeCart_Heartbeat',{'ChargeCart_Heartbeat_dummydata' : 1 })
  File "msg_send.py", line 25, in send_msg
    encoded_data = check_message.encode(data)
  File "/usr/local/lib/python3.7/dist-packages/cantools/database/can/message.py", line 737, in encode
    strict)
  File "/usr/local/lib/python3.7/dist-packages/cantools/database/can/message.py", line 695, in _encode
    scaling)
  File "/usr/local/lib/python3.7/dist-packages/cantools/database/utils.py", line 86, in encode_data
    little_packed = formats.little_endian.pack(unpacked)[::-1]
OverflowError: Signed integer value 1 out of range.`

**Comment by HybridShivam** [comment]
Any updates???

**Comment by juleq** [comment]
A signed integer of length 1 makes no sense.
