### ISSUE TITLE
EncodeError should be raised in case of inconsistent MUX values in the data given to Message._encode

### ISSUE THREAD

**Issue by AlexDLSy** [cantools/cantools#342]
In the protected method _encode of class database.can.Message, if the message is multiplexed, there is no check regarding consistency of multiplexer values among the given signals.

For example, if the user gives the multiplexor signal the value 0x2 and only specifies other signals which are linked to multiplexor value 0x1, all the given signal values are dumped and the frame is sent with signals linked to mux value 0x2 with value 0 or signal.initial, without any notification.

Since that is obviously not what any user would intend to do, and most likely a user input mistake, I suggest the following 2 improvements :

1. Add a feature that raises an EncodeError if _encode is called  with an inconsistent set of mux values across signals.
That would involve adding a 'mux_value' attribute to Signal class and increase the accessibility to _codecs attribute in Message class.

2. Add a feature that automatically selects the correct multiplexor signal value if missing, based on a consistent set of multiplexed signals.

I will submit a pull request if I get the time to work on this (not before Mid Oct I think)

**Comment by andlaus** [comment]
https://github.com/cantools/cantools/pull/350 should have fixed this? if not, please reopen this issue.
