### ISSUE TITLE
Where to add SYM Direction Field?

### ISSUE THREAD

**Issue by samc1213** [cantools/cantools#408]
In PCAN, you can define a message as send, receive, or bi-directional:

![image](https://user-images.githubusercontent.com/9583514/157726946-9e620181-fedc-480c-ba9f-69addc6e07fa.png)

This is very useful to help generate I/O code, since you can know which messages are inputs vs outputs with respect to your ECU.

However, I don't see a great place to put this information in the cantools `Message` object. `send_type` and `senders` both don't seem exactly right, given `send_type` is more of a DBC concept. Can I please have some guidance on where this flag could go? Or if perhaps it's decoded somewhere already that I'm missing?

**Comment by andlaus** [comment]
in the current cantools data model, only signals exhibit receivers. if SYM only specifies receivers for frames,  you can add the receiving ECU to all signals of that frame. (that's what the ARXML loader does.)

**Comment by samc1213** [comment]
Agreed that only signals exhibit receivers, but Messages exhibit senders which is interesting. Would Message.senders would be a better place?

**Comment by andlaus** [comment]
> Would Message.senders would be a better place?

I agree, but it's already implemented like this ;): https://github.com/cantools/cantools/blob/master/cantools/database/can/message.py#L78

**Comment by samc1213** [comment]
@andlaus is there a reason we can't change Message.senders? I'm really happy to put this either in Message.senders or Signal.receivers. However, it feels like the SYM file is breaking the data structures of cantools. The only way I can see to do it is use some magic strings like "ECU" and "Peripherals" to differentiate between a Send and Receive message. SYM does not have node names like other file formats. See my PR to get a sense of what I was thinking. Thanks for your help

**Comment by andlaus** [comment]
Sorry for the belated answer, I somehow missed your message. anyway, I'd like to answer to the best of my ability:

> is there a reason we can't change Message.senders?

I suppose the main reason is that nobody needed this so far and no setters were added to the respective properties. (PR welcome :)) Also, you can "unofficially" do this by changing the `_senders` and `_receivers` (mind the underscore) attributes of the respective objects.

> However, it feels like the SYM file is breaking the data structures of cantools.

yeah, cantools is aimed at the traditional signal-based communication model of the automotive industry, i.e., formats like DBC, ARXML, and KCD should work pretty well. Your mileage with other communication models like CANopen may vary considerably. Patches are welcome, though. (Provided that they do not regress the currently working stuff too much.)

> The only way I can see to do it is use some magic strings like "ECU" and "Peripherals" to differentiate between a Send and Receive message. SYM does not have node names like other file formats. See my PR to get a sense of what I was thinking. 

I think that the solution which you came up with is quite nice :)
