### ISSUE TITLE
Type annotations not available for code which calls cantools.

### ISSUE THREAD

**Issue by Hnasar** [cantools/cantools#421]
Type annotations were added to a few packages in !378 but these are not used by clients of cantools.

When I try to use cantools, mypy errors:
```
error: Skipping analyzing "cantools": module is installed, but missing library stubs or py.typed marker
```

This is because packages that include type annotations in the source code should include an empty file `py.typed` in the package (or a parent package). The mypy docs which show an example using setuptools:

https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

 See [PEP-561](https://peps.python.org/pep-0561/) for details.

**Comment by andlaus** [comment]
good point. can you make a pull request for this? (modulo the unit tests, cantools already should have type annotations.)
