### ISSUE TITLE
CAN-FD initialization error on PEAK device

### ISSUE THREAD

**Issue by sortkim** [cantools/cantools#441]
Hi!

I tested can-fd function with PCAN device and I checked the initialization error on the PEAK device.

source code 
 handle = can.interface.Bus(bustype='pcan', channel='PCAN_USBBUS1', bitrate=500000, fd= True) 

 -> Exception has occurred: PcanCanInitializationError

but vector VN1630 worked fine.

The pcan driver version is 4.3.0.16563.

Be careful when using peak can devices.

thanks

**Comment by andlaus** [comment]
this is almost certainly a [python-can](https://github.com/hardbyte/python-can) issue or an issue with the pcan driver, i.e., cantools can do nothing about it (?). I am a bit surprised anyway, though: I routinely use a PEAK device with can-fd enabled. I'm using socketcan on linux, do you use windows?

**Comment by juleq** [comment]
I would probably step through to find out if this exception can provide more information.

Further: There is a Peak Settings app for Windows now. I think you can enable logging for the PCAN Basic API.

Probably most important: I recently also had some shaky behaviour using PCAN Basic from C#. I used Peak Flash to update the interface firmware to 8.6.1 or something and that made it stable again for me. I think the instability first occurred with a driver update for the interface.

**Comment by sortkim** [comment]
I am using Windows10.

**Comment by juleq** [comment]
Python-can is the project that you are using for bus access and that is raising the error you see. Cantools is a project that you can use on top to allow symbolic can access (encoding/decoding based on definitions in dbc/kcd/sym files, etc.).

I would:
- Update to the latest pcan usb driver
- Update to the latest pcan basic API
- Update the firmware of the pcan usb to latest
- Check if the problem persists

If the problem persists, open an issue in the python-can project.

**Comment by sortkim** [comment]
I'm moving this issue to python-can.
Thank you for your advice.
