### ISSUE TITLE
ARXML problem: decode data are not what expected.

### ISSUE THREAD

**Issue by linpanusst** [cantools/cantools#445]
Hi, Miss or Mr.
I have a question when I decode the can files via "arxml". Here are the descriptions.
![image](https://user-images.githubusercontent.com/37352923/175495875-dfd7702c-96a3-4711-a1c5-4d6832d13a5f.png)
Please see this picture. The decoded values which are **False** and **Disabled**. They should be uint8 or uint16 values. Eg. They should be 0, 1 or 2...
This picture is the definition of one signal.
![image](https://user-images.githubusercontent.com/37352923/175496622-c6c3a04c-aebc-4d98-80c7-c6335c1eb5c8.png)
It seams that the code put the "Description value" in the value column.
Could you please help me to fix this problem?
If you need more description or pictures. Please contact my e-mail of linpan_usst@163.com
Looking forward to hearing from you.

**Comment by andlaus** [comment]
I suppose that you need to ask the provider of the tool which you are using; cantools seems to be completely unrelated to it. I'm closing the issue for this reason. Feel free to reopen it if I made a mistake...

**Comment by andlaus** [comment]
(I can have a closer look if you provide a sample data file.)

**Comment by linpanusst** [comment]
Hi, I am glad to provide sample data. Could I send such data to this address: [github@poware.org](mailto:github@poware.org)? 
Or could you please send me hello via the e-mail address linpan_usst@163.com? Then I can direct send you sample data.

**Comment by linpanusst** [comment]
To provide clean sample data. I need about 3 days. Thank you so much.

**Comment by andlaus** [comment]
> Hi, I am glad to provide sample data. Could I send such data to this address: [github@poware.org](mailto:github@poware.org)?

yes, that would work. Alternatively, you can create a [gist](https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) and post the link to it here...

> To provide clean sample data. I need about 3 days. Thank you so much.

don't worry, I'll probably need a few days to inspect it thereafter anyway...

**Comment by linpanusst** [comment]
Hi, I have sent you the test data and its related arxml format database. Thank you for your time.

**Comment by linpanusst** [comment]
Hi, here is the gist link. However, the test data which is xxx.blf can not be uploaded. I have sent you via e-mail [github@poware.org](mailto:github@poware.org). Please check.
On the gist, it is my python can decode code. Its ugly.

**Comment by andlaus** [comment]
thanks for the data. I'll have a look, but since I'm pretty busy at the moment it might take a while before I can have a look...

**Comment by linpanusst** [comment]
Ok, thanks a lot. Feel free to e-mail if you need more information.

**Comment by Lit-fish-auto** [comment]
> Ok, thanks a lot. Feel free to e-mail if you need more information. [testdata.zip](https://github.com/cantools/cantools/files/9017920/testdata.zip)

I use the following code：

db = cantools.database.load_file('abc.arxml')
all_message = db.messages
print(al_lmessage)

The above code reads frame in _arxm_l, and can only read the signal directly hung under message.(message.signal_trees)
In fact, many signals in arxml are hung under the pdu, and these signals cannot be read.
I don't know whether the above is a bug or There is a problem with my way of reading load_file

can you help me?

**Comment by Lit-fish-auto** [comment]
Generally, the arxml format of CANFD is   Frame :: Container-PDU :: I-signal-PDU :: Signal
If arxml is in the above format, thenThe method of  load_ file（abc.arxml） cannot read the signal.

Above, how should this form of arxml be read? or  is the bug ？
