### ISSUE TITLE
can't load dbc with utf-8 characters

### ISSUE THREAD

**Issue by fr0zenrain** [cantools/cantools#478]
db = cantools.database.load_file(sys.argv[1]) throw erros
cantools.database.UnsupportedDatabaseFormatError: DBC: "Invalid syntax at line 28, column 10: " SG_ TBOX>>!<<´ÎÈí¼þ°æ±¾ºÅ$_W : 15|8@0+(1,0)[0|255] "" Vector__XXX""

it seems dbc.py's  token_specs regex just only identify ascii characters, so it has a plan to fix utf-8 issue? thanks!

**Comment by juleq** [comment]
Could you provide a sample file? Does Vector CANdb++ open that file?

**Comment by andlaus** [comment]
you could also try if
```python
db = cantools.database.load_file(sys.argv[1], encoding="utf8")
```
does the trick...

**Comment by fr0zenrain** [comment]
> you could also try if
> 
> ```python
> db = cantools.database.load_file(sys.argv[1], encoding="utf8")
> ```
> 
> does the trick...

not work

**Comment by fr0zenrain** [comment]
with an example dbc file, and find the "SG_" line, replace with other language ,i'm not sure wether dbc specification is support or not. i found some software support it,but CANdb++ 3.1 not support.
SG_ TBOXVersion : 15|8@0+(1,0)[0|255] "" Vector__XXX
SG_ TBOX版本 : 15|8@0+(1,0)[0|255] "" Vector__XXX

**Comment by juleq** [comment]
Since CANdb++ is authoritative to the dbc file format, I think this will have to be considered unsupported.
