### ISSUE TITLE
Documentation site missing `NamedSignalValue`

### ISSUE THREAD

**Issue by Hnasar** [cantools/cantools#486]
Per index.rst (https://github.com/cantools/cantools/blob/master/docs/index.rst), `NamedSignalValue` should be defined right after Decimal, but it's missing

https://cantools.readthedocs.io/en/latest/#cantools.database.can.signal.Decimal

https://github.com/cantools/cantools/blob/master/cantools/database/can/signal.py#L83

**Comment by zariiii9003** [comment]
I think this can be closed.
https://cantools.readthedocs.io/en/latest/#cantools.database.can.signal.NamedSignalValue
