### ISSUE TITLE
[suggestion] update API doc in readthedocs

### ISSUE THREAD

**Issue by ziyangfu** [cantools/cantools#487]
The last successful build of doc was 2 years ago, and add many new features at the period of 2 years. maybe rebuild the doc manually is a good idea. I do not know why automatic build failed recently.

**Comment by zariiii9003** [comment]
A [new version of the docs](https://cantools.readthedocs.io/en/latest/) has been built with version 38, but the images added in #252 and #277 fail to load because of the relative paths.

Maybe @erzoe could fix that?

**Comment by erzoe** [comment]
@zariiii9003 I have opened a pull request: https://github.com/cantools/cantools/pull/512
