### ISSUE TITLE
The signal.comment can not parse the chinese characters

### ISSUE THREAD

**Issue by songzuolong** [cantools/cantools#499]
Python parses dbc files, for Chinese garbled characters in siganl.comment

**Comment by andlaus** [comment]
if your file is does not use UTF-8 encoding, you need to explicitly pass it via the `encoding` parameter for [`load_file()`](https://github.com/cantools/cantools/blob/master/cantools/database/__init__.py#L104)

**Comment by songzuolong** [comment]
my dbc file: VAL_ 345 WiprHoodOpenInde 0 "关闭提醒" 1 "触发提醒" ;
use the db = cantools.database.load_file("c:\\Users\\szl\\Desktop\\DBC\\MS11_DBC.dbc",encoding="utf-8") 
but still garbled。
ǰ��δ��Ԥ����Ť����Ч��

**Comment by songzuolong** [comment]
I have sloved this problem， 
you are right， i need to add the encoding parameter for load_file().
I.e.  db = cantools.database.load_file("c:\Users\szl\Desktop\DBC\MS11_DBC.dbc",encoding="gbk")

**Comment by songzuolong** [comment]
> if your file is does not use UTF-8 encoding, you need to explicitly pass it via the `encoding` parameter for [`load_file()`](https://github.com/cantools/cantools/blob/master/cantools/database/__init__.py#L104)

thanks
