### ISSUE TITLE
filterlabeling validation

### ISSUE THREAD

**Issue by Testato** [cantools/cantools#505]
I use SavvyCan for create Dbc file
Normally it put at the end of the file this:
BA_DEF_DEF_ "filterlabeling" true;

When I open this file by cantools list command it say that true is not correct, so i change it to:
BA_DEF_DEF_ "filterlabeling" 1;

So my question:
Is Savvycan wrong to use true instead of 1 ?
Or is Cantools that should accept 1 but also true ?

**Comment by juleq** [comment]
I think Savvycan might be wrong. Numeric values are without quotes, enums and strings with quotes. There is no boolean type, so true without quotes does not exist.

**Comment by Testato** [comment]
Thanks, it will be solved by SavvyCan
