### ISSUE TITLE
Support for DBC decoding pandas dataframes

### ISSUE THREAD

**Issue by MatinF** [cantools/cantools#544]
Hi there,

We are interested in trying out this repo for one of our projects, which involves DBC decoding raw CAN bus data in the form of pandas dataframes. Is this possible with the repository? We were not able to find any examples of code achieving this.

**Comment by andlaus** [comment]
I don't know what pandas dataframes are, but if you can get a sequence of payloads and the associated frame IDs, it basically comes down to this:

```python
import cantools

# [...]

db = cantools.database.load_file("my_nice_communication_description.dbc")

for frame_id, payload in unpacked_pandas_dataframes:
  print(db.decode_message(frame_id, payload)
```

**Comment by andlaus** [comment]
Okay, I'm closing this issue for now. If the answer above does not work, don't hesitate to add further comments...
