### ISSUE TITLE
Generated SYM Enum Lines Exceed Max Length

### ISSUE THREAD

**Issue by ciepme** [cantools/cantools#642]
Hi, I'm having an issue working with cantool's generated SYM files where the enumeration definition exceeds the maximum allowable line length for tools like PCAN Symbol Editor (Error 001: Syntax error - Line too long). The issue appears after approx 1,000 characters. Considering using newlines between each value to remedy.

**Comment by andlaus** [comment]
can you provide a patch?

**Comment by ciepme** [comment]
> can you provide a patch?

Yes, I will be working toward this.

**Comment by swaldhoer** [comment]
Should this issue not have been closed when https://github.com/cantools/cantools/pull/643 was merged?
