### ISSUE TITLE
Flexray XML file parsing support

### ISSUE THREAD

**Issue by drZWzheng** [cantools/cantools#674]
Now the Flexray protocol is widely used in car domain, it has the huge demand to have a tool to parse the XML data format file, but the cantools is not support to parse the format currently. As a participant, i strongly recommended to  support parsing Flexray data format.

**Comment by andlaus** [comment]
I'm not sure if flexray support is in the scope of a project named "cantools", and flexray is also on its way out in the automotive industry (the FlexRay consortium dissolved in 2010), but I suppose nobody would object if you forked the cantools project (probably renaming it to something akin "flextools") and added this support...
